### ISSUE TITLE
Server won't fully start

### ISSUE THREAD

**Issue by EastSideCode** [SimbCo/httpster#30]
Any time I try to start httpster, it gets hung up after \lib\middleware\query.js

Any ideas on what could be wrong?

**Comment by simb** [comment]
I have not seen that issue, but I will look at it today. Since I have not added any new functionality in a while I have not tried to install it recently and perhaps something is borked with one of the dependencies.

Did you just install and it wont work.  Or has it been installed for a while and just stopped working?

**Comment by EastSideCode** [comment]
I first installed it yesterday, so it hasn't worked before.

**Comment by simb** [comment]
I got around to looking into this today.  I am not having any issues.  Do you mind telling me what os and version of node you are using?

**Comment by simb** [comment]
I can't replicate this issue and no response so I think the ticket is dead.
